export const ADD_PRODUCT = 'cart/ADD_PRODUCT'
export const INCREASE_PRODUCT_QUANTITY = 'cart/INCREASE_PRODUCT_QUANTITY'
export const DECREASE_PRODUCT_QUANTITY = 'cart/DECREASE_PRODUCT_QUANTITY'
export const REMOVE_PRODUCT = 'cart/REMOVE_PRODUCT'